import localFont from "next/font/local";
import "./globals.css";
import React from "react";
import { NavBar } from "@/components/NavBar";
import { Inter } from "next/font/google";
import { TopCAtegory } from "@/components/TopCategory";
import Footer from "@/components/Footer";
import RootLayoutWrapper from './wrapper/client/RootLayoutWrapper';



const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});

const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

const inter = Inter({ subsets: ["latin"] });


export const metadata = {
    title: "Ekhonni.com",
    description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
    const token = localStorage.getItem("token");
    return (
      <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <RootLayoutWrapper authentication={{ token: token || "" }}>
          <div className="w-full">
              <NavBar placeholder="What are you looking for?" />
              <TopCAtegory />
          </div>
          <main>{children}</main>
          <div className="bg-gray-800 text-white">
              <Footer />
          </div>
      </RootLayoutWrapper>
      </body>
      </html>
    );
}
