import localFont from 'next/font/local';
import './globals.css';
import React from 'react';
import { NavBar } from '@/components/NavBar';
import { Inter } from 'next/font/google';
import { TopCAtegory } from '@/components/TopCategory';
import Footer from '@/components/Footer';
import RootLayoutWrapper from './wrapper/client/RootLayoutWrapper';
import CustomErrorBoundary from '@/components/ErrorBoundary';
import SessionWrapper from './wrapper/client/SessionWrapper'
import { ErrorBoundary } from 'react-error-boundary';
import ErrorFallback from '@/components/ErrorFallback';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});

const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

const inter = Inter({ subsets: ['latin'] });


export const metadata = {
  title: 'Ekhonni.com',
  description: 'Generated by create next app',
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
    <RootLayoutWrapper>
      <CustomErrorBoundary>
        <div className="w-full">
          <NavBar placeholder="What are you looking for?" />
          <TopCAtegory />
        </div>

        <SessionWrapper>

          <main>{children}</main>

        </SessionWrapper>
        <div className="bg-gray-800 text-white">
          <Footer />
        </div>
      </CustomErrorBoundary>
    </RootLayoutWrapper>

    </body>
    </html>
  );
}
