
import localFont from 'next/font/local';
import './globals.css';
import React from 'react';
import { Inter } from 'next/font/google';
import Footer from '@/components/Footer';
import RootLayoutWrapper from './wrapper/client/RootLayoutWrapper';
import CustomErrorBoundary from '@/components/ErrorBoundary';
import SessionWrapper from './wrapper/client/SessionWrapper'
import { Toaster } from 'sonner';
import { ConditionalFooter, ConditionalNavBar, SessionNavBar } from '@/components/SessionNavbar';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});

const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

const inter = Inter({ subsets: ['latin'] });


export const metadata = {
  title: 'Ekhonni.com',
  description: 'Generated by create next app',
};


export default function RootLayout({ children }: { children: React.ReactNode }) {

  return (
    <html lang="en" suppressHydrationWarning>
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
    <RootLayoutWrapper>
      <CustomErrorBoundary>
        <Toaster />
        <SessionWrapper>
          <div className="w-full">
           <ConditionalNavBar />
          </div>
          <main className="flex-grow overflow-auto">{children}</main>

          <div className="bg-gray-800 text-white">
            <ConditionalFooter />
          </div>
        </SessionWrapper>
      </CustomErrorBoundary>
    </RootLayoutWrapper>
    </body>
    </html>
  );
}
