spring:

  application:
    name: ${APPLICATION_NAME}

  main:
    allow-bean-definition-overriding: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASSNAME}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: ${JPA_GENERATE_DDL:true}
    defer-datasource-initialization: ${JPA_DEFER_DATASOURCE_INIT:false}
    show-sql: ${JPA_SHOW_SQL:false}
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL:false}
        highlight_sql: ${JPA_HIGHLIGHT_SQL:false}

  sql:
    init:
      platform: ${SQL_INIT_PLATFORM:postgresql}
      mode: ${SQL_INIT_MODE:never}

  security:
    jwt:
      secret: ${JWT_SECRET}
      access:
        token:
          expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
    refresh:
      token:
        expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

    admin:
      email: ${ADMIN_EMAIL}
      password: ${ADMIN_PASSWORD}

  constant:
    public:
      urls: ${PUBLIC_URLS}
    user:
      urls: ${USER_URLS}
    admin:
      urls: ${ADMIN_URLS}
    email-verification-url: ${EMAIL_VERIFICATION_URL}
    password-reset-url: ${PASSWORD_RESET_URL}

  mail:
    host: ${SMTP_MAIL_HOST}
    port: ${SMTP_MAIL_PORT}
    username: ${SMTP_MAIL_USERNAME}
    password: ${SMTP_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

  output:
    ansi:
      enabled: ALWAYS

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO
    com.ekhonni: DEBUG

server:
  address: ${SERVER_ADDRESS}

sslcommerz:
  domain: ${SSLCOMMERZ_DOMAIN}
  store-id: ${SSLCOMMERZ_STORE_ID}
  store-password: ${SSLCOMMERZ_STORE_PASSWORD}
  success-url: ${BASE_PAYMENT_URL}/success
  fail-url: ${BASE_PAYMENT_URL}/fail
  cancel-url: ${BASE_PAYMENT_URL}/cancel
  ipn-url: ${SSLCOMMERZ_IPN_URL}
  api-url: ${SSLCOMMERZ_API_URL}
  validation-api-url: ${SSLCOMMERZ_VALIDATION_API_URL}
  merchant-trans-id-validation-api-url: ${SSLCOMMERZ_MERCHANT_TRANS_ID_VALIDATION_API_URL}
  connection-timeout: ${SSLCOMMERZ_CONNECTION_TIMEOUT}
  read-timeout: ${SSLCOMMERZ_READ_TIMEOUT}
  allowed-ips: ${SSLCOMMERZ_ALLOWED_IPS}

upload:
  dir: ${UPLOAD_DIR}

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
      base-path: /actuator
      cors:
        allowed-origins: "*"
        allowed-methods: GET,POST
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  info:
    env:
      enabled: true
    git:
      enabled: true
    build:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      sla:
        http.server.requests: 10ms, 100ms
    enable:
      jvm: true
      process: true
      system: true
      http: true
  health:
    diskspace:
      enabled: true
    db:
      enabled: true
    redis:
      enabled: true
    mail:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    description: Ekhonni Backend Service
    version: 2.0.0
  contact:
    email: ekhonni72@gmail.com
    team: Backend Team
  environment: ${spring.profiles.active}
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
      file-name-pattern: logs/archived/application.%d{yyyy-MM-dd}.%i.log

  cloudinary:
    cloud_name : ${CLOUDINARY_CLOUD_NAME},
    api_key : ${CLOUDINARY_API_KEY},
    api_secret : ${CLOUDINARY_API_SECRET}
